main: com.infogroup.infotag.InfoTag
name: InfoTag
authors: [pixar02, Ktar5]
website : "bit.ly/InfoBoardReborn_spigot & bit.ly/InfoBoardReborn_bukkit"
depend: [PlaceholderAPI]

commands:
  InfoTag:
    usage: /<command> [args]
    discription:
    aliases: [it, infot, itag]


permissions:
  it.*:
    default: op
    children:
      it.create: true
      it.toggle: true
      it.view: true
  it.toggle:
    default: true
  it.view:
    default: true